// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
export const Index = {
  "todo-app": {
    name: "todo-app",
    type: "components:ui",
    registryDependencies: [],
    component: () => import("ui/todo-app.vue"),
    file: "@/registry/ui/todo-app.vue",
  },
};
